---
title: "reproducible survey access"
format: html
---

## Set up

```{r}
library(qualtRics)
library(tidyr)
library(knitr)
library(ggplot2)
library(readr)
library(kableExtra)
library(dplyr)
```

## Read in API key

```{r}
key_file <- read_lines("/tmp/qualtrics-key.txt")

qualtrics_api_credentials(api_key = key_file, base_url = "ucsb.co1.qualtrics.com", install = FALSE, overwrite = FALSE)

usethis::edit_r_environ()
```

## Read in surveys

```{r}
surveys <- all_surveys()

kable(surveys) %>%
    kable_styling()
```

## Selecting the survey we want to work with

```{r}
i <- which(surveys$name == "Survey for Data Science Training")
# look into the name column in survey with this name and give it the value "i"

id <- surveys$id[i]

```


## Getting questions using survey ID

```{r}
questions <- survey_questions(id) #all questions from that survey

kable(questions) %>%
    kable_styling()


```

## Getting survey responses

```{r}
survey_results <- fetch_survey(id) #getting the survey results
glimpse(survey_results)
```

## How long have you been programming? Responses to question 2

```{r}
q2 <- survey_results %>% 
  select(Q2) %>% 
  group_by(Q2) %>% # group by all the options in q2
  summarise(n = n()) %>% # counting how many are in each option in Q2

kable(q2, col.names = c("How long have you been programming?", "Number of responses")) %>% 
  kable_styling()
```

## Question 3

```{r}
q3 <- survey_results %>% 
  select (Q3) %>% 
  group_by(Q3) %>% 
  summarise(n = n())

ggplot(q3, 
       aes(x = Q3,
           y = n)) +
  geom_col() +
  labs(x = "What language do you currently use most frequently?") +
  theme_minimal()

q3_text <- survey_results %>% 
  select(Q3_7_TEXT) %>% 
  drop_na()

kable(q3_text, col.names = "Other responses to what langugage do you currently use most frequently") %>% 
  kable_styling()


```


```{r}
q3_complete <- survey_results %>% 
  select(Q3)

q3_text_complete <- survey_results %>% 
  select(Q3_7_TEXT) %>% 
  rename(Q3 = Q3_7_TEXT) %>% 
  drop_na()

q3_all <- bind_rows(q3_complete, q3_text_complete) %>%  # need to remove "Other" via filter or select
  group_by(Q3) %>% 
  summarise(n = n()) %>% 
  dplyr::filter(!Q3 %in% c("Other"))

```

## Google Forms

```{r}
library(googlesheets4)
```

Read google form results google sheet

```{r}
responses <- read_sheet("https://docs.google.com/spreadsheets/d/1CSG__ejXQNZdwXc1QK8dKouxphP520bjUOnZ5SzOVP8/edit?usp=sharing")
```

Exploring data
```{r}
dplyr::glimpse(responses)

```

Changing column names

```{r}
questions <- colnames(responses)[2:5]
dplyr::glimpse(questions)

names(questions) <- paste0("Q", seq(1,4)) #removes space between 1 and 2
#paste function is whatever character you introduce + space
#paste0 will remove the space between the character and the number 

questions

colnames(responses) <- c("Timestamp", names(questions))

glimpse(responses)

#could use mutate and rename function in tidyverse
```

